app/src/main/java/com/example/cherry_pick_android/presentation/ui/firstKeyword/FirstKeywordFragment.kt, app/src/main/res/drawable/ic_keyword_search.xml, app/src/main/res/drawable/ic_keyword_search_background.xml, app/src/main/res/layout/fragment_first_keyword.xml
최초 키워드 등록 레이아웃입니다
Hi-fi에 맞는 키워드 등록 UI 구현
=> [Feat] 최초 키워드 레이아웃 구현

.idea/deploymentTargetDropDown.xml, app/src/main/res/drawable/ic_nav_background.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/values/themes.xml
=> [Feat] : 코드 정리

app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/dialog/KeywordDialog.kt, app/src/main/res/layout/fragment_search_keyword.xml
이슈 번호 : #44 
- 레이아웃 오류 수정했습니다 (ConstraintLayout 연결부분)
- 다이얼로그가 0.5초뒤에 사라지도록 조정했습니다.
피그마와 동일
=> [Refactor] Dialog 조정, 레이아웃 수정, 폰트적용

app/src/main/java/com/example/cherry_pick_android/presentation/ui/infrom/InformSettingActivity.kt
=> [Fix] 코드 오류 해결

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt, app/src/main/res/drawable/ic_job_button.xml, app/src/main/res/drawable/ic_job_button_clicked.xml, app/src/main/res/layout/activity_job_group.xml, app/src/main/res/layout/item_job_group.xml
이슈 번호 : #번호
우선, gridview 안에 item만 바뀌고 나머지는 크게 달라진 것 없습니다.
=> [Feat] : GridViewItem 수정

app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt, app/src/main/res/layout/activity_job_group.xml
이슈 번호 : #74 
- 1 완료 버튼 활성화&색상 변경
- 2
=> [Fix] : 직군 버튼 수정

app/build.gradle, app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/data/module/datastore/DataStoreModule.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/repository/UserIdRepositoryImpl.kt, app/src/main/java/com/example/cherry_pick_android/domain/model/UserId.kt, app/src/main/java/com/example/cherry_pick_android/domain/repository/UserIdRepository.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/login/LoginViewModel.kt
이슈 번호 : #71 
- Data store 이용
현재까지 구현한 내용이며 완성된 결과물은 아닙니다!
=> [Feat] 자동로그인 구현

app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialog.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialogInterface.kt, app/src/main/res/drawable/bg_camera_dialog.xml, app/src/main/res/drawable/ic_camera_dialog_text.xml, app/src/main/res/layout/dialog_camera.xml
=> [Feat] : 카메라 다이얼로그 임시 추가

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/cherry_pick_android/data/remote/repository/UserDataRepositoryImpl.kt, app/src/main/java/com/example/cherry_pick_android/domain/repository/UserDataRepository.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/login/LoginViewModel.kt
이슈 번호 : #79 
- 직군 페이지 완료버튼을 누를때 생기는 오류 수정
=> [Fix] 직군 완료 버튼 로직 수정

app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
이슈 번호 : #83 
- 가독성 증가를 위한 리팩토링
그리드 뷰에선 해당 아이템들의 뷰를 각각 참조하기 매우 어렵다고 합니다.
현재는 클릭된 버튼을 다시 눌러 취소하는 방법이 최선인것같습니다!
=> [Refactor] 직군 어뎁터 코드 가독성 증가를 위한 리팩토링

app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/DeleteUserResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/DeleteUserService.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/UserDeleteDialog.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/UserDeleteDialogInterface.kt, app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/login/LoginViewModel.kt, app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/mypage/MyPageViewModel.kt, app/src/main/res/drawable/bg_user_delete_dialog.xml, app/src/main/res/drawable/ic_user_delete_logo.xml, app/src/main/res/layout/dialog_delete_user.xml, app/src/main/res/values/strings.xml
이슈 번호 : #93 
- 로그아웃 기능
- 회원탈퇴 기능
로그아웃은 간단한 alertDialog로 구현했습니다.
회원탈퇴는 커스텀 다이얼로그를 만들어 구현했습니다.
=> [Feat] 로그아웃 및 회원탈퇴기능 구현

app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/repository/UserDataRepositoryImpl.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/request/user/updateNameRequest.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/DeleteUserResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/DeleteUserService.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/UserNameUpdateService.kt, app/src/main/java/com/example/cherry_pick_android/domain/repository/UserDataRepository.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
이슈 번호 : #96 
- 유저 닉네임 변경 업데이트
유저닉네임 변경과 토큰 갱신값을 수정했습니다
=> [Feat] 유저 닉네임 변경 업데이트 및 토큰갱신

app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialogInterface.kt, app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/mypage/MyPageViewModel.kt
이슈 번호 : #번호
- 1
- 2
통신 오류 포함되어있습니다.
=> [Feat] : 프로필 이미지API

app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
이슈 번호 : #104 
- 생년월일, 성별 갱신
- 생년월일 매핑함수 구현(ex 20000314 -> 2000.03.14)
커밋내용 그대로입니다!
=> [Feat] 유저 생년월일, 성별 갱신

app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/data/module/api/AppInterceptor.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/request/ArticleLikeDTO.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleLikeResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleUnlikeResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleLikeService.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleUnlikeService.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/util/ApplicationClass.kt, app/src/main/res/values/strings.xml
이슈 번호 : #115 
- 토큰 오류 해결
- 스크랩 api 구현
스크랩은 작업중이라 클릭하시면 오류발생합니다! 
토큰 오류는 해결했습니다!
=> [Feat] 스크랩 구현

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleLikeResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleUnlikeResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleLikeService.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt, app/src/main/res/drawable/splash_logo.xml, app/src/main/res/drawable/splash_text.xml, app/src/main/res/values/themes.xml
이슈 번호 : #118
- 스플레시 화면 틀 구축
- 공유하기 uri 추가
스플레시 화면은 디자인이 수정되는대로 수정하겠습니다!
=> [Refactor] 공유하기 uri추가 및 스플레시 화면 틀 구축

app/src/main/java/com/example/cherry_pick_android/data/data/ArticleItem.kt, app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleIndustryResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleSearchIndustryService.kt, app/src/main/java/com/example/cherry_pick_android/presentation/adapter/IndustryAdapter.kt, app/src/main/java/com/example/cherry_pick_android/presentation/adapter/KeywordListAdapter.kt, app/src/main/java/com/example/cherry_pick_android/presentation/adapter/NewsRecyclerViewAdapter.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/AdapterInteractionListener.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/KeywordFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordDetailFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt, app/src/main/res/layout/fragment_search_keyword.xml, app/src/main/res/layout/fragment_search_keyword_detail.xml, app/src/main/res/menu/menu_article_sort.xml
이슈 번호 : #121 
- 직군 선택으로 기사 요청
- 검색 서비스 -> 직군 서비스로 변경
직군 선택, 정렬 선택에 따라 HomeNewsFragment의 API 요청을 받아옵니다.
=> [Feat] 기사 직군별 요청

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/DeleteImageResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/UpLoadImageResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/UpdateNameResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/UserDeleteImageService.kt, app/src/main/java/com/example/cherry_pick_android/domain/model/UserData.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialog.kt, app/src/main/res/xml/provider_paths.xml
이슈 번호 : #번호
- 1 카메라 연결 확인용
- 2
=> [Feat] : 프로필 이미지 업로드

app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleDetailResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleScrapResponse.kt, app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleScrapService.kt, app/src/main/java/com/example/cherry_pick_android/presentation/adapter/ScrapAdapter.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/scrap/DeleteScrapListener.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/scrap/ScrapTrueFragment.kt, app/src/main/res/layout/item_scrap_news.xml
=> [Feat] 스크랩 좋아요 기능 구현

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/cherry_pick_android/presentation/ui/infrom/InformSettingActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt, app/src/main/res/values/strings.xml
이슈 번호 : #143 
- 스트링 값 변경
현재 뷰모델 충돌로 앱 강제종료가 있어서 merge 합니다.
=> [Feat] : 최신순, 오래된순으로 변경 (#143)

app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/gpt/GptActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/KeywordFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/first/FirstKeywordFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordDetailFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt, app/src/main/java/com/example/cherry_pick_android/presentation/ui/scrap/ScrapTrueFragment.kt, app/src/main/res/layout/fragment_first_keyword.xml, app/src/main/res/layout/fragment_keyword.xml, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/layout/fragment_scrap_true.xml, app/src/main/res/layout/fragment_search_keyword_detail.xml, app/src/main/res/layout/fragment_search_list.xml, app/src/main/res/values/strings.xml
=> Refactor/144 UI refactor

README.md
이슈 번호 : #
- 리드미 작성
우리 프로젝트를 설명한 리드미를 작성했습니다! 추가할 내용 있으면 추가하겠습니다~
=> [Docs] ReadMe 작성
